INSERT INTO genres (genre)
VALUES ('Action'),
       ('Comedy'),
       ('Drama'),
       ('Thriller'),
       ('Horror'),
       ('Sci-Fi'),
       ('Romance'),
       ('Documentary'),
       ('Animation'),
       ('Reality');

INSERT INTO movie_tags (genre_id, tag)
VALUES (1, 'Martial Arts'),
       (1, 'Espionage'),
       (1, 'Superhero'),
       (1, 'Heist'),
       (2, 'Slapstick'),
       (2, 'Romantic Comedy'),
       (2, 'Dark Comedy'),
       (2, 'Parody'),
       (3, 'Period Drama'),
       (3, 'Crime Drama'),
       (3, 'Family Drama'),
       (3, 'Legal Drama'),
       (4, 'Psychological Thriller'),
       (4, 'Crime Thriller'),
       (4, 'Mystery'),
       (4, 'Political Thriller'),
       (5, 'Slashers'),
       (5, 'Haunted House'),
       (5, 'Demons'),
       (5, 'Zombie'),
       (6, 'Space Opera'),
       (6, 'Cyberpunk'),
       (6, 'Time Travel'),
       (6, 'Dystopian'),
       (7, 'Romantic Drama'),
       (7, 'Coming of Age'),
       (7, 'Steamy Romance'),
       (7, 'Dark Romance'),
       (8, 'Political Documentary'),
       (8, 'Social Issue'),
       (8, 'Science Documentary'),
       (8, 'Nature Documentary'),
       (9, 'Kids Animation'),
       (9, 'Adult Animation'),
       (9, 'Comic Book Animation'),
       (9, 'Anime');

SELECT *
FROM movie_tags;